technologies = [
    "Security architecture",
    "Cloud Security",
    "Azure",
    "Defender",
    "Sentinel",
    "Entra",
    "Purview",
    "SIEM",
    "SOAR",
    "DevSecOps",
    "CI/CD Security",
    "ISO 27001",
    "NIST",
    "TISAX",
    "GDPR",
    "Burp Suite",
    "OWASP ZAP",
    "Nmap",
    "Nuclei",
    "sqlmap",
    "Metasploit",
    "ffuf",
    "JavaScript",
    "Node.js",
    "Python",
    "Bash",
    "HTTP",
    "TLS",
    "OAuth2",
    "OIDC",
    "JWT",
    "SAML",
    "WebSockets",
    "ISO 27001",
    "GDPR",
    "PCI-DSS",
    "EBIOS",
    "ISO 27005",
    "Node.js",
    "TypeScript",
    "REST APIs",
    "Microservices",
    "Docker",
    "Git",
    "PostgreSQL",
    "MongoDB",
    "CI/CD",
    "AWS",
    "Azure",
    "GCP",
    "Node.js",
    "React.js",
    "MySQL",
    "REST APIs",
    "JavaScript",
    "TypeScript",
    "C",
    ".NET",
    "Python",
    "Java",
    "AL/Business Central",
    "Python",
    "Docker",
    "Docker Compose",
    "React",
    "CI/CD",
    "Jenkins",
    "Git",
    "Linux",
    "Unix",
    "Python",
    "Bash",
    "Jenkins",
    "GitLab",
    "GitHub Actions",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Git",
    "Ansible",
    "Terraform",
    "Prometheus",
    "Grafana",
    "Firewalls",
    "VPN",
    "IDS/IPS",
    "SIEM",
    "Network Security",
    "ISO 27001",
    "NIST",
    "ANSSI",
    "React",
    "Django",
    "GCP",
    "BigQuery",
    "Dataflow",
    "Python",
    "SQL",
    "Software testing",
    "QA",
    "AS400",
    "IBM i",
    "RPG",
    "RPGLE",
    "CLLE",
    "Embedded SQL",
    "DB2 for i",
    "SYNON/CA 2E",
    "JIRA",
    "Batch Processing",
    "SDLC",
    "Infrastructure as Code",
    "GitLab Workflow",
    "CI/CD",
    "Ansible",
    "Molecule",
    "Bash",
    "ZSH",
    "Python",
    "TDD",
    "SQL",
    "SQL",
    "Git",
    "XML",
    "Unix",
    "Java",
    "HTML/XPath",
    "Selenium WebDriver",
    "Jenkins",
    "AutoIT",
    "Jira",
    "Squash",
    "TestNG",
    "JUnit",
    "Katalon Studio",
    "Robot Framework",
    "Python",
    "React",
    "Java",
    "CI/CD",
    "Docker",
    "Kubernetes",
    "Airflow",
    "Cloud",
    "SQL",
    "NoSQL",
    "MongoDB",
    "Neo4j",
    "Elasticsearch",
    "Redis",
    "Kibana",
    "Grafana",
    "Pandas",
    "Linux",
    "IaC",
    "Angular",
    "Vue.js",
    "Azure Data Factory",
    "Azure Synapse",
    "GCP BigQuery",
    "Dataflow",
    "Python",
    "SQL",
    "Spark",
    "Airflow",
    "Prefect",
    "Docker",
    "CI/CD",
    "Kafka",
    "Pub/Sub",
    "C#",
    ".NET",
    "ASP.NET Core",
    "REST APIs",
    "SQL Server",
    "Software Architecture",
    "Application Security",
    "Performance",
    "Python",
    "Flask",
    "Eve",
    "REST APIs",
    "JSON-RPC",
    "SOAP/XML",
    "Git",
    "CLI",
    "Postman",
    "Insomnia",
    "MongoDB",
    "Docker",
    "Kubernetes",
    "TDD",
    "Secure IT Infrastructure",
    "Systems",
    "Storage",
    "Networks",
    "Security",
    "Cisco",
    "Aruba",
    "Dell",
    "HPE",
    "IBM",
    "TypeScript",
    "JavaScript",
    "Angular",
    "Node.js",
    "Firestore",
    "Redis",
    "Git",
    "GCP Cloud Run",
    "Cloud Functions",
    "Pub/Sub",
    "Secret Manager",
    "Logging",
    "CI",
    "TDD",
    "Agile",
    ".NET MAUI",
    "Blazor",
    "C#",
    ".NET 8+",
    "iOS",
    "Android",
    "REST APIs",
    "OOP",
    "SOLID",
    "Design Patterns",
    "Git",
    "WinForms",
    "Azure Pipelines",
    "GitHub Actions",
    "Firewalls",
    "VPN",
    "IDS/IPS",
    "Routers",
    "Switches",
    "Wireless Access Points",
    "TCP/IP",
    "VLAN",
    "OSPF",
    "Wireshark",
    "Bash",
    "Python",
    "Firewalls",
    "IDS",
    "Network Analysis",
    "Fortinet",
    "Palo Alto",
    "Check Point",
    "Cisco CCNA/CCNP Security",
    "AWS Cloud Practitioner",
    "Azure AZ-900",
    "Java",
    "Cucumber",
    "Selenium",
    "Playwright",
    "Git",
    "Jira",
    "Xray",
    "Confluence",
    "SQL",
    "BDD/Gherkin",
    "Agile/Scrum",
    "Node.js",
    "Express",
    "Nest.js",
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "REST APIs",
    "JSON",
    "WebSockets",
    "OAuth",
    "JWT",
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Git",
    "Next.js",
    "React",
    "Drupal Headless",
    "APIs",
    "Azure data services",
    "Python",
    "SQL",
    "Hadoop",
    "Spark",
    "Kafka",
    "Java",
    "Spring Boot",
    "Python",
    "Node.js",
    "TypeScript",
    "REST APIs",
    "SOLID",
    "SonarQube",
    "Git",
    "CI/CD",
    "OpenAI",
    "Anthropic",
    "Mistral",
    "RAG",
    "LangChain",
    "LangGraph",
    "PHP",
    "Python",
    "MariaDB",
    "MySQL",
    "Linux",
    "Git",
    "CI/CD",
    "Blazor",
    "Web API",
    "ASP.NET MVC",
    "C#",
    "Entity Framework",
    "Bootstrap",
    "JavaScript",
    "jQuery",
    "Oracle",
    "SQL Server",
    "UML",
    "DevOps",
    "Git",
    "Kotlin",
    "Java",
    "Micronaut",
    "Spring Boot",
    "OAuth",
    "SSO",
    "Okta",
    "Auth0",
    "Keycloak",
    "ForgeRock",
    "OIDC",
    "JWT",
    "SAML",
    "MFA",
    "Azure",
    "AWS",
    "GCP",
    "CI/CD",
    "GCP",
    "GCE",
    "GKE",
    "BigQuery",
    "Cloud Functions",
    "CI/CD",
    "Jenkins",
    "GitLab CI",
    "Google Cloud Build",
    "Kubernetes",
    "Terraform",
    "Google Deployment Manager",
    "Python",
    "Bash",
    "Prometheus",
    "GCP",
    "Security Command Center",
    "Cloud Armor",
    "Cloud Identity",
    "IAM",
    "Encryption",
    "Firewalls",
    "VPN",
    "ISO 27001",
    "NIST",
    "GDPR",
    "Python",
    "Bash",
    "DevSecOps",
    "SIEM",
    "AWS",
    "EC2",
    "S3",
    "RDS",
    "EKS",
    "Lambda",
    "VPC",
    "IAM",
    "Windows",
    "Linux",
    "SQL Server",
    "MySQL",
    "PowerShell",
    "Bash",
    "Python",
    "CloudFormation",
    "Terraform",
    "Docker",
    "Kubernetes",
    "Ansible",
    "Chef",
    "Puppet",
    "CloudWatch",
    "Grafana",
    "Prometheus",
    ".NET Core 8/9",
    "C# 12",
    "Entity Framework Core",
    "SQL Server",
    "ASP.NET Core Web API",
    "REST",
    "JWT",
    "Hangfire",
    "Clean Architecture",
    "Repository Pattern",
    "Git",
    "DevOps",
    "Visual Studio",
    "ChatGPT",
    "Claude",
    "Gemini",
    "Cursor",
    "Linux",
    "NGINX",
    "Microservices",
    "Distributed Systems",
    "Docker",
    "Virtualization",
    "Cloud",
    "APIs",
    "HTTP(S)",
    "DNS",
    "SSL/TLS",
    "Security",
    "Grafana",
    "ELK",
    "Zipkin",
    "Python",
    "C++",
    "C#",
    "Java",
    "OOP",
    "Functional Programming",
    "SOLID",
    "Agile",
    "distributed systems",
    "multithreading",
    "quantitative libraries",
    "Systems",
    "Servers",
    "Networks",
    "Databases",
    "Java",
    "Python",
    "C#",
    "PHP",
    "JavaScript",
    "Network architecture",
    "Infrastructure Security",
    "IT Risk",
    "Security Standards",
    "Incident Management",
    "SLA",
    "Network Administration",
    "SQL",
    "Spark",
    "Hadoop",
    "AWS",
    "Azure",
    "GCP",
    "Python",
    "APIs",
    "Microservices",
    "PHP 8+",
    "Symfony",
    "API Platform",
    "Doctrine ORM",
    "SQL",
    "MySQL",
    "MariaDB",
    "PostgreSQL",
    "Redis",
    "RabbitMQ",
    "Kafka",
    "Elasticsearch",
    "Linux",
    "Docker",
    "Kubernetes/OpenShift",
    "Git/GitLab",
    "CI/CD",
    "PHPUnit",
    ".NET",
    "C#",
    "Web development",
    "Java",
    "Angular",
    "Azure Data Factory",
    "Microsoft Fabric",
    "Azure SQL",
    "Analysis Services",
    "SQL",
    "T-SQL",
    "Python",
    "C#",
    "Git",
    "DevOps",
    "Kubernetes",
    "GCP",
    "GitLab CI",
    "Cloud Infrastructure",
    "CI/CD",
    "Production Deployment",
    "Security by Design",
    "Shell",
    "Bash",
    "YAML",
    "Ansible",
    "GitLab",
    "Cloud provisioning",
    "CI/CD",
    "Next.js",
    "GitHub Copilot",
    "Python",
    "Java/WebObjects",
    "Red Hat",
    "AIX",
    "Ubuntu",
    "Python",
    "DevOps",
    "Ansible",
    "GitLab CI",
    "Docker",
    "Kubernetes",
    "WAF",
    "F5 NAP",
    "Vulnerability Management",
    "Hardening",
    "Python",
    "Go",
    "Shell",
    "OpenStack",
    "CIS",
    "Playwright",
    "TypeScript",
    "Java",
    "JUnit",
    "Mockito",
    "REST APIs",
    "Microservices",
    "GitLab CI/CD",
    "Docker",
    "Selenium",
    "Java",
    "Playwright",
    "TypeScript",
    "Karate",
    "Gherkin",
    "Postman",
    "Jira Xray",
    "Jenkins",
    "GitLab CI",
    "ISTQB",
    "C",
    "C++",
    "C#",
    "PL/SQL",
    "Oracle",
    "Git",
    "Linux",
    "Windows",
    "OOP",
    "Agile/Scrum",
    "React",
    "Angular",
    "Vue.js",
    "Java",
    "Node.js",
    ".NET",
    "Python",
    "PHP",
    "MySQL",
    "PostgreSQL",
    "Full-stack development",
    "Windows",
    "AIX",
    "Linux",
    "Oracle",
    "SQL Server",
    "MySQL",
    "PostgreSQL",
    "SAP",
    "PepLink",
    "HP switches",
    "Fortigate",
    "Dell EMC",
    "Lotus Notes",
    "LAN",
    "WAN",
    "Wi-Fi",
    "Python",
    "Java",
    "JavaScript",
    "Selenium",
    "Cypress",
    "Playwright",
    "Appium",
    "Robot Framework",
    "pytest",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "Git",
    "Jira",
    "Azure DevOps",
    "AWS",
    "Azure",
    "GCP",
    "Docker",
    "Kubernetes",
    "JMeter",
    "Locust",
    "Postman",
    "Microsoft 365",
    "Systems Administration",
    "Access Control",
    "Digital Workplace Support",
    "Web development",
    "IT support",
    "internal/external web solutions",
    "Linux",
    "Docker",
    "Kubernetes",
    "GitLab CI",
    "Jenkins",
    "GitHub Actions",
    "AWS",
    "Azure",
    "GCP",
    "Terraform",
    "Ansible",
    "Grafana",
    "Prometheus",
    "ELK",
    "Networking",
    "Reverse Proxy",
    "Load Balancing",
    "Microservices",
    "Redis",
    "Laravel",
    "PHP",
    "Vue.js 3",
    "Flutter",
    "Git",
    "REST APIs",
    "GCP",
    "BigQuery",
    "BigTable",
    "Scala",
    "Java",
    "Hadoop",
    "Spark",
    "Kafka",
    "Big Data",
    "Penetration Testing",
    "Cybersecurity",
    "Python",
    "Django",
    "Flask",
    "PostgreSQL",
    "DynamoDB",
    "JavaScript",
    "Bootstrap",
    "AWS S3",
    "SES",
    "CloudWatch",
    "ECS",
    "EC2",
    "API Gateway",
    "GitLab",
    "Docker",
    "Terraform",
    "Windows",
    "Linux",
    "VMware",
    "OpenStack",
    "Docker",
    "Kubernetes",
    "Git",
    "Jenkins",
    "Puppet",
    "Ansible",
    "Nagios",
    "Zabbix",
    "ELK",
    "Perl",
    "Python",
    "PHP",
    "JavaScript",
    "JSON",
    "YAML",
    "Windows",
    "Linux",
    "VMware ESXi",
    "VLAN",
    "Routing",
    "VPN",
    "DNS",
    "DHCP",
    "WiFi",
    "Firewalls",
    "VMware",
    "Proxmox",
    "VLAN",
    "TCP/IP",
    "DNS",
    "DHCP",
    "VPN",
    "Firewalls",
    "WiFi",
    "Windows",
    "Linux",
    "Monitoring",
    "Backup",
    "Virtualization",
    "TypeScript",
    "CSS",
    "React Hooks",
    "Vite",
    "Zustand",
    "Wouter",
    "CI/CD",
    "Docker",
    "Kubernetes",
    "Python",
    "FastAPI",
    "Pydantic",
    "Microsoft Fabric",
    "PySpark",
    "Azure Data Factory",
    "SQL",
    "Data Lake",
    "APIs",
    "Windows",
    "Linux",
    "Virtualization",
    "Network Security",
    "AWS",
    "Azure",
    "Playwright",
    "TypeScript",
    "JavaScript",
    "Robot Framework",
    "Python",
    "REST",
    "SOAP",
    "Postman",
    "Selenium",
    "Cucumber",
    "Karate",
    "Postman",
    "Java",
    "Python",
    "Ruby",
    "REST",
    "CI/CD",
    "ISTQB",
    "Functional testing",
    "REST",
    "JSON",
    "XML",
    "Postman",
    "basic automation",
    "Salesforce Sales Cloud",
    "Service Cloud",
    "Marketing Cloud",
    "Experience Cloud",
    "Jira",
    "Xray",
    "TestRail",
    "Zephyr",
    "Provar",
    "Selenium",
    "Postman",
    "SOQL",
    "SOSL",
    "Apex",
    "Git",
    "CI/CD",
    "Azure",
    "DevOps",
    "Cloud",
    ".NET",
    "C#",
    "React",
    "TypeScript",
    "SQL",
    "NoSQL",
    "Docker",
    "Git",
    "Kafka",
    "RabbitMQ",
    "ELK",
    "Cisco Catalyst",
    "WLC",
    "ISE",
    "Meraki",
    "Catalyst Center",
    "WiFi",
    "VPN SSL/IPSec",
    "Azure",
    "Databricks",
    "Python",
    "SQL",
    "Hadoop",
    "Cloudera",
    "Hive",
    "Impala",
    "HDFS",
    "PySpark",
    "Kafka",
    "Cassandra",
    "HBase",
    "C# .NET 8",
    "ASP.NET Core",
    "Entity Framework",
    "SQL Server",
    "HTML",
    "CSS",
    "JavaScript",
    "jQuery",
    "Bootstrap",
    "Visual Studio 2022",
    "Git",
    "Azure DevOps",
    "Azure App Services",
    "Azure SQL",
    "Azure Storage",
    "Microsoft Sentinel",
    "Azure",
    "Splunk",
    "Google SecOps",
    "Logic Apps",
    "APIs",
    "Scripting",
    "Cloud Security",
    "Docker",
    "Kubernetes",
    "Cloud",
    "Python",
    "Bash",
    "Java",
    "Ansible",
    "Security Monitoring",
    "Dataiku",
    "Starburst",
    "BigQuery",
    "SQL",
    "Python",
    "MLOps",
    "Cloud",
    "GCP",
    "GKE",
    "Cloud Run",
    "Cloud Functions",
    "Cloud SQL",
    "VPC",
    "Pub/Sub",
    "Terraform",
    "Pulumi",
    "IAM",
    "GitHub Actions",
    "GitLab CI",
    "Cloud Build",
    "Bash",
    "Python",
    "Go",
    "Docker",
    "Kubernetes",
    "Systems & Networks",
    "Cloud Computing",
    "Docker",
    "Kubernetes",
    "InfluxDB",
    "MySQL",
    "Grafana",
    "Prometheus",
    "CI/CD",
    "IoT Security",
    "IoT",
    "Data Engineering",
    "Software Development",
    "Windows",
    "Linux",
    "LAN",
    "WAN",
    "VPN",
    "Servers",
    "Monitoring",
    "Backup",
    "Java",
    "Spring Boot",
    "Apache Camel",
    "OAuth2",
    "OIDC",
    "OpenIAM",
    "Microservices",
    "Event-driven architecture",
    "Databases",
    "CI/CD",
    "Git",
    "Sonar",
    "SOLID",
    "Agile",
    "Bitbucket",
    "Bamboo",
    "Docker",
    "Java",
    "Maven",
    "Tomcat",
    "Git",
    "GitLab",
    "Jenkins",
    "SonarQube",
    "Black Duck",
    ".NET 9",
    "Blazor",
    "SQL Server",
    "REST",
    "Gherkin",
    "xUnit",
    "Playwright",
    "Postman",
    "Azure DevOps",
    "Application Insights",
    "Salesforce",
    "Kubernetes",
    "Cloud Native",
    "CI/CD",
    "GitOps",
    "Flutter",
    "Laravel",
    "Web/App Development",
    "AI",
    "Backend development",
    "Programming",
    "OOP",
    "React",
    "Next.js",
    "TypeScript",
    "AI",
    "PHP",
    "Laravel",
    "HTML",
    "CSS",
    "JavaScript",
    "Vue",
    "Node.js",
    "HTML",
    "CSS",
    "JavaScript",
    "PHP",
    "Python",
    "Node.js",
    "React",
    "Angular",
    "Laravel",
    "MySQL",
    "MongoDB",
    "Networks",
    "Systems",
    "Azure",
    "Microsoft Fabric",
    "Azure Data Factory",
    "Data Lake",
    "Azure Functions",
    "SQL",
    "Databricks",
    "PySpark",
    "Delta",
    "DLT",
    "Python",
    "Power BI",
    "Git",
    "Postman",
    "ReadyAPI",
    "Selenium",
    "Playwright",
    "Robot Framework",
    "JMeter",
    "Azure DevOps",
    "Python",
    "JavaScript",
    ".NET",
    "C#",
    "ASP.NET",
    "Blazor",
    "Microsoft SQL",
    "Agile",
    "DevOps",
    "C#",
    ".NET",
    "WPF",
    "ASP.NET Core",
    "Web API",
    "SQL Server",
    "Docker",
    "Azure DevOps",
    "Jira",
    "Bitbucket",
    "Git",
    "Playwright",
    "Selenium",
    "Cypress",
    "TCP/IP",
    "HTTP/HTTPS",
    "DNS",
    "TLS",
    "VLAN",
    "Git",
    "GitLab",
    "Jira",
    "Jenkins",
    "Cybersecurity",
    "Infrastructure",
    "Networks",
    "IT support/ticketing",
    "SQL",
    "PL/SQL",
    "Java",
    "Test Automation",
    "SDET",
    "SQL",
    "Spark",
    "Hadoop",
    "AWS",
    "Azure",
    "GCP",
    "Python",
    "APIs",
    "Microservices",
    "Selenium",
    "Cypress",
    "API testing",
    "CI/CD",
    "Playwright",
    "TestCafe",
    "Azure",
    "AWS",
    "Terraform",
    "Terratest",
    "GitHub Actions",
    "Ansible",
    "Puppet",
    "GitLab",
    "Jenkins",
    "ARM",
    "Azure CLI",
    "Jira Xray",
    "DevOps",
    "Informatica",
    "Cloud",
    "CI/CD",
    "Java",
    "Python",
    "SQL",
    "OpenStack",
    "Kubernetes",
    "GitLab",
    "Jenkins",
    "Nexus",
    "Prometheus",
    "Grafana",
    "Checkmarx",
    "Jira",
    "Robot Framework",
    "Docker",
    "Kubernetes",
    "GitLab CI",
    "Azure DevOps",
    "Linux",
    "Shell",
    "Azure",
    "AWS",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana",
    "ELK",
    "APIs",
    "Playwright",
    "Selenium",
    "Cypress",
    "Robot Framework",
    "Karate",
    "Postman",
    "Java",
    "JavaScript",
    "Node.js",
    "HTML",
    "CSS",
    "ISO 27001",
    "NIST",
    "EBIOS",
    "SOC",
    "SIEM",
    "EDR",
    "IAM",
    "Cloud Security",
    "Networks",
    "Systems",
    "Virtualization",
    "HTML",
    "CSS",
    "JavaScript",
    "Java",
    "PHP",
    "Node.js",
    "Python",
    "Ruby",
    ".NET",
    "Full-stack development",
    "PHP",
    "JavaScript",
    "Laravel",
    "CakePHP",
    "Python",
    "React",
    "PostgreSQL",
    "MySQL",
    "REST",
    "Python",
    "FastAPI",
    "Next.js",
    "Tailwind CSS",
    "TypeScript",
    "AI",
    "React",
    "Next.js",
    "FastAPI",
    "Voice AI"]
technologies=set(technologies)

# liste.py
niveaux_etudes = [
    "sans diplôme",
    "niveau bac",
    "bac",
    "baccalauréat",
    "bac+1",
    "bac +1",
    "bac+2",
    "bac +2",
    "BTS",
    "DUT",
    "DEUST",
    "DTS",
    "bac+3",
    "bac +3",
    "licence",
    "licence professionnelle",
    "bachelor",
    "BUT",
    "bac+4",
    "bac +4",
    "maîtrise",
    "bac+5",
    "bac +5",
    "master",
    "master 1",
    "master 2",
    "MBA",
    "diplôme d'ingénieur",
    "ingénieur",
    "cycle ingénieur",
    "bac+6",
    "bac+7",
    "doctorat",
    "PhD",
    "doctorant",
    "école d'ingénieurs",
    "école de commerce",
    "formation supérieure",
    "enseignement supérieur",
    "non précisé"
]

experience = [
    "0 an", "aucune expérience", "sans expérience",
    "débutant", "junior", "profil junior",

    "1 an", "1 année", "1+ an", "au moins 1 an",
    "1 à 2 ans", "1-2 ans",

    "2 ans", "2 années", "2+ ans", "au moins 2 ans",
    "2 à 3 ans", "2-3 ans",

    "3 ans", "3 années", "3+ ans", "au moins 3 ans",
    "3 à 5 ans", "3-5 ans",

    "4 ans", "4 années", "4+ ans",

    "5 ans", "5 années", "5+ ans", "au moins 5 ans",
    "5 à 10 ans", "5-10 ans",

    "6 ans", "7 ans", "8 ans", "9 ans", "10 ans",
    "plus de 10 ans",

    "intermédiaire",
    "confirmé",
    "senior",
    "expert",
    "expérimenté",

    "expérience professionnelle",
    "expérience requise",
    "expérience souhaitée",
    "expérience exigée",
    "non précisé"
]
type_contrat = [
    "CDI",
    "CDD",
    "CDI / CDD",
    "stage",
    "stage rémunéré",
    "stage non rémunéré",
    "alternance",
    "apprentissage",
    "contrat d'apprentissage",
    "contrat de professionnalisation",
    "intérim",
    "mission",
    "freelance",
    "indépendant",
    "consultant",
    "vacation",
    "temps plein",
    "temps partiel",
    "emploi saisonnier",
    "contrat temporaire",
    "contrat permanent",
    "VIE",
    "volontariat",
    "bénévolat",
    "non précisé"
]